[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ["py312"]

[tool.flake8]
max-line-length = 120

[tool.poetry]
name = "power-flow-game"
version = "0.0.0"
description = "A game based on electricity market coupling"
authors = ["Robbie Muir <robbiemuir7@gmail.com>", "Roman Cantu <>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.*"
pypsa = "^0.34.1"
pandas = "^2.2.3"
numpy = "^2.2.5"
plotly = "^6.1.2"
livereload = "^2.7.1"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
flake8 = "^7.2.0"
pytest = "^8.3.5"
flake8-pyproject = "^1.2.3"
