from typing import Protocol, runtime_checkable

from src.app.game_repo.base import BaseGameStateRepo
from src.engine.engine import Engine
from src.models.game_settings import GameSettings
from src.models.game_state import GameState
from src.models.ids import GameId, PlayerId
from src.models.message import (
    GameToPlayerMessage,
    GameUpdate,
    InternalMessage,
    PlayerToGameMessage,
    ToGameMessage,
)
from src.new_game.new_game import GameInitializer


@runtime_checkable
class FrontEndMessageHandler(Protocol):
    # A generic stub for the front end implementation
    def handle_player_messages(self, msgs: list[GameToPlayerMessage]) -> None: ...


class GameManager:
    def __init__(
        self,
        game_repo: BaseGameStateRepo,
        game_engine: Engine,
        front_end_interface: FrontEndMessageHandler,
    ) -> None:
        assert isinstance(game_repo, BaseGameStateRepo)
        assert isinstance(front_end_interface, FrontEndMessageHandler)
        self.game_repo = game_repo
        self.game_engine = game_engine
        self.front_end = front_end_interface

    def update_players(self, game_id: GameId, players: list[PlayerId]) -> None:
        game_state = self.game_repo.get_game_state(game_id)
        game_update_messages = [GameUpdate(game_id=game_id, player_id=p, game_state=game_state, message="") for p in players]
        self.front_end.handle_player_messages(msgs=game_update_messages)  # type: ignore

    def handle_player_message(self, game_id: GameId, msg: PlayerToGameMessage) -> None:
        # TODO Make this atomic
        game_state = self.game_repo.get_game_state(game_id)
        updated_game_state = self._handle_message(game_id=game_id, game_state=game_state, msg=msg)
        self.game_repo.update_game_state(updated_game_state)

    def _handle_message(self, game_id: GameId, game_state: GameState, msg: ToGameMessage) -> GameState:
        
        gs, messages = self.game_engine.handle_message(game_state=game_state, msg=msg)

        msgs_to_players = [e for e in messages if isinstance(e, GameToPlayerMessage)]
        msgs_to_self = [e for e in messages if isinstance(e, InternalMessage)]

        ids = gs.players.human_player_ids
        game_update_messages = [GameUpdate(game_id=game_id, player_id=p, game_state=gs, message="") for p in ids]

        self.front_end.handle_player_messages(msgs=msgs_to_players + game_update_messages)

        if not len(msgs_to_self):
            return gs

        assert len(msgs_to_self) == 1, "There should be at most one internal message generated by the engine."

        return self._handle_message(game_id=game_id, game_state=gs, msg=msgs_to_self[0])

    @classmethod
    def new_game(cls, game_repo: BaseGameStateRepo, player_names: list[str]) -> GameId:
        game_id = game_repo.generate_game_id()
        settings = GameSettings()
        game_initializer = GameInitializer(settings=settings)
        new_game_state = game_initializer.create_new_game(game_id=game_id, player_names=player_names)
        game_repo.add_game_state(game=new_game_state)
        return game_id
